function []=funcCompareKinematicXYZ(trainSet,xyz_estimation,par_set)
% Compare Fwd Kinematic with Exp in Cam frame
figure('Position',[100,400,600,400])
subplot(3,1,1)
plot(trainSet.tip_exp(:,2),'Color','r','LineWidth',2,'LineStyle','-.')
hold on
plot(xyz_estimation(:,1),'Color','b','LineWidth',2)
title('Tip Position(m) on X-Axis')
legend('Experiment','Model')
ylim([-0.05,0.2])
subplot(3,1,2)
plot(trainSet.tip_exp(:,3),'Color','r','LineWidth',2,'LineStyle','-.')
hold on
plot(xyz_estimation(:,2),'Color','b','LineWidth',2)
title('Tip Position(m) on Y-Axis')
ylim([-0.05,0.2])
subplot(3,1,3)
plot(trainSet.tip_exp(:,4),'Color','r','LineWidth',2,'LineStyle','-.')
hold on
plot(xyz_estimation(:,3),'Color','b','LineWidth',2)
title('Tip Position(m) on Z-Axis')
ylim([0,0.2])
% Calculate normalized RMSE and plot
error_matrix=trainSet.tip_exp(:,2:4)-xyz_estimation;
RMSE_x = sqrt(mean((error_matrix(:,1)).^2))
RMSE_y = sqrt(mean((error_matrix(:,2)).^2))
RMSE_z = sqrt(mean((error_matrix(:,3)).^2))
figure('Position',[500,400,600,400])
subplot(3,1,1)
plot((trainSet.tip_exp(:,2)-xyz_estimation(:,1))./par_set.L,'Color','r','LineWidth',2,'LineStyle','-.')
title('Normalized Error on X-Axis')
% legend('Experiment','Model')
% ylim([-0.2,0.2])
subplot(3,1,2)
plot((trainSet.tip_exp(:,3)-xyz_estimation(:,2))./par_set.L,'Color','r','LineWidth',2,'LineStyle','-.')
title('Normalized Error on Y-Axis')
% legend('Experiment','Model')
% ylim([-0.2,0.2])
subplot(3,1,3)
plot((trainSet.tip_exp(:,4)-xyz_estimation(:,3))./par_set.L,'Color','r','LineWidth',2,'LineStyle','-.')
title('Normalized Error on Z-Axis')
legend('Experiment','Model')
ylim([-0.2,0.2])
end